name: CI
on:
  push:
    branches: [ 8.0 ]
  pull_request:
    branches: [ 8.0 ]

jobs:
  build:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: oliveiradigital/odoo-br
          dockerfile: Dockerfile
          tag_with_ref: true